general:
  enable_logging: true
  log_level: "info"
  default_language: "system"
  roms_directory: "ROMs"
  lists_directory: "list"
  temp_directory: "temp"
  logs_directory: "logs"

api:
  crocdb_api_url: "https://api.crocdb.net"
  max_search_pages: 5

mirrors:
  download_splits: 10
  connections_per_server: 10

updates:
  check_tool_update_on_startup: true
  tool_repository_url: "https://github.com/Oraculo-adm/CLIDOWNROM"